package problempackage;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class KnapsackGUI extends JFrame {
    private JLabel nritems;
    private JTextField textamount;
    private JLabel nrseed;
    private JTextField textseed;
    private JLabel nrcapacity;
    private JButton rozwiążButton;
    private JTextArea items;
    private JLabel typeitems;
    private JPanel rozw;
    private JTextArea resultbox;
    private JTextField textcapacity;

    public KnapsackGUI() {
        setTitle("KnapsackGUI");
        setContentPane(rozw);
        setPreferredSize(new Dimension(600, 800));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setVisible(true);

        rozwiążButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int lowerBound = 1; // dolny zakres
                int upperBound = 10; // górny zakres
                int n = Integer.parseInt(textamount.getText());
                int seed = Integer.parseInt(textseed.getText());
                int capacity = Integer.parseInt(textcapacity.getText());
                Problem problem = new Problem(n, seed, lowerBound, upperBound);
                items.setText(problem.toString());
                Result result = problem.solve(capacity);
                resultbox.setText(result.toString());
            }
        });
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new KnapsackGUI();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rozw = new JPanel();
        rozw.setLayout(new GridBagLayout());
        nritems = new JLabel();
        nritems.setText("   Liczba rodzajów przedmiotów");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        rozw.add(nritems, gbc);
        textamount = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rozw.add(textamount, gbc);
        nrseed = new JLabel();
        nrseed.setText("   Ziarno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        rozw.add(nrseed, gbc);
        textseed = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rozw.add(textseed, gbc);
        nrcapacity = new JLabel();
        nrcapacity.setText("   Pojemność plecaka");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        rozw.add(nrcapacity, gbc);
        rozwiążButton = new JButton();
        rozwiążButton.setText("Rozwiąż");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rozw.add(rozwiążButton, gbc);
        typeitems = new JLabel();
        typeitems.setText("   Dostępne przedmioty");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        rozw.add(typeitems, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Przedmioty w plecaku");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 3.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        rozw.add(label1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.weightx = 2.0;
        gbc.weighty = 20.0;
        gbc.fill = GridBagConstraints.BOTH;
        rozw.add(scrollPane1, gbc);
        items = new JTextArea();
        items.setEditable(false);
        items.setText("");
        scrollPane1.setViewportView(items);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridheight = 8;
        gbc.fill = GridBagConstraints.BOTH;
        rozw.add(scrollPane2, gbc);
        resultbox = new JTextArea();
        resultbox.setEditable(false);
        scrollPane2.setViewportView(resultbox);
        textcapacity = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rozw.add(textcapacity, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.BOTH;
        rozw.add(panel1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rozw;
    }
}
